series: Intermediate C++
title: STL Containers
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Use templates to define generic classes.
language: C++
tags:
  - Core
extra_resources:
  - link: http://www.cplusplus.com/reference/stl/
    title: STL containers reference (cplusplus.com).
  - link: http://www.learncpp.com/cpp-tutorial/16-2-stl-containers-overview/
    title: Another tutorial (leancpp.com)
connections:
  - series: Intermediate C++
    title: Class Templates